config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index' 
  resources :reservas
  resources :tabela_precos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord

end

app/models/periodo.rb
class Periodo < ApplicationRecord

end

app/models/reserva.rb
class Reserva < ApplicationRecord
  belongs_to :tipo_cliente
end

app/models/tabela_preco.rb
class TabelaPreco < ApplicationRecord
  belongs_to :hotel
  belongs_to :tipo_cliente
  belongs_to :periodo
end

app/models/tipo_cliente.rb
class TipoCliente < ApplicationRecord
    has_many :reservas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @reservas = Reserva.all
  end

  def show
    @reserva = Reserva.find(params[:id])
  end
end

app/controllers/hotel_controller.rb
class HotelController < ApplicationController
end

app/controllers/periodo_controller.rb
class PeriodoController < ApplicationController
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
    require 'date'
    require 'time'

    before_action :set_find, only: [:show, :edit, :update, :destroy]

    def index
      @reservas = Reserva.all
      @tipo_clientes = TipoCliente.all
    end

    def show
      @tabela_precos = TabelaPreco.all
      @reservas = Reserva.all
      @tipo_clientes = TipoCliente.all
    
      @differ = calcula_dias_corridos(@reserva.date_starting, @reserva.date_exit)
      @weekdays = calcula_dias_semana(@reserva.date_starting, @reserva.date_exit)
      @weekend_days = (@differ.to_i - @weekdays)


      @totalReserva = 0
      @tabela_preco_total = []
      @tabela_preco_semana = []
      @tabela_preco_fds = []

            @tabela_precos.each do |tabela_preco|
              if tabela_preco.tipo_cliente.type_client == @reserva.tipo_cliente.type_client
                if @weekdays > 0 && tabela_preco.periodo.periodo == "Semana"
                  @tabela_preco_semana << {nome: tabela_preco.hotel.nome,
                                          classe: tabela_preco.hotel.classe,
                                          periodo: tabela_preco.periodo.periodo, 
                                          tipo_cliente: tabela_preco.tipo_cliente.type_client,
                                          total: (@weekdays * tabela_preco.preco)}                                                       
                end
              end
            end

            @tabela_precos.each do |tabela_preco|
              if tabela_preco.tipo_cliente.type_client == @reserva.tipo_cliente.type_client
                if @weekend_days > 0 && tabela_preco.periodo.periodo == "Fim de semana"
                  @tabela_preco_fds << {nome: tabela_preco.hotel.nome, 
                                          periodo: tabela_preco.periodo.periodo,
                                          classe: tabela_preco.hotel.classe, 
                                          tipo_cliente: tabela_preco.tipo_cliente.type_client,
                                          total: (@weekend_days * tabela_preco.preco)}
                end
              end
            end

            #Falta validar empate de valores pelo criterio de classe do hotel
          if @weekend_days > 0 && @weekdays > 0 
              @tabela_preco_semana.each do |tab1|
                @tabela_preco_fds.each do |tab2|
                  if tab1[:nome] == tab2[:nome]
                    @tabela_preco_total << {nome: tab2[:nome], classe: tab2[:classe], total: (tab1[:total]+tab2[:total])}
                  end
                end
              end
            elsif @weekdays > 0
              @tabela_preco_semana.each do |tab1| 
                @tabela_preco_total << {nome: tab1[:nome], classe: tab1[:classe], total: (tab1[:total])}   
              end
            elsif @weekend_days > 0
              @tabela_preco_fds.each do |tab2| 
                @tabela_preco_total << {nome: tab2[:nome], classe: tab2[:classe], total: (tab2[:total])}   
              end
            else
              @tabela_preco_total << "Sem dados pra processar"
          end


    end

    def calcula_dias_corridos(date_starting, date_exit)
      @time_date_starting = Time.parse(date_starting)
      @time_date_exit = Time.parse(date_exit)
      (((@time_date_exit - @time_date_starting) / 3600 )/24)
    end

    def calcula_dias_semana(date_starting, date_exit)
      (((Date.parse(date_starting))..(Date.parse(date_exit)) ).select {|d| (1..5).include?(d.wday) }.size - 1 )
    end

    def calcula_dias_fim_de_semana(differ, weekdays)
      (@differ.to_i - @weekdays.to_i) 
    end

    def new
      @reserva = Reserva.new
      @tipo_clientes = TipoCliente.all
    end

    def create
        @reserva = Reserva.new(reserva_params)
        @tipo_clientes = TipoCliente.all
      if @reserva.save
        flash[:notice] = 'Reserva efetuada com sucesso!'
        redirect_to @reserva
      else
        flash[:alert] = 'Erro'
        render :new
      end
    end

    def edit
      @reservas = Reserva.all
      @tipo_clientes = TipoCliente.all
    end
  
    def update
      if @reserva.update(reserva_params)
        redirect_to @reserva
      else
        render :edit
      end
    end

    def destroy
      @reserva.destroy
      redirect_to @reserva, notice: "Reserva excluida com sucesso!"
    end

  private

  def reserva_params
    params.require(:reserva).permit(:tipo_cliente_id, :date_starting, :date_exit)
  end

  def set_find
    @reserva = Reserva.find(params[:id])
  end

end

app/controllers/tabela_precos_controller.rb
class TabelaPrecosController < ApplicationController

  before_action :set_find, only: [:show, :edit, :update, :destroy]

  def index
    @tabela_precos = TabelaPreco.all
    @hoteis = Hotel.all
    @tipo_clientes = TipoCliente.all
    @periodos = Periodo.all
  end

  def show
    @reserva = Reserva.find(params[:id])
    @tabela_precos = TabelaPreco.all
    @hoteis = Hotel.all
    @tipo_clientes = TipoCliente.all
    @periodos = Periodo.all
  end

  def create
    @tabela_preco = TabelaPreco.new(tabela_preco_params)
    @hoteis = Hotel.all
    @tipo_clientes = TipoCliente.all
    @periodos = Periodo.all
  if @tabela_preco.save
    flash[:notice] = 'Preco incluido com sucesso na tabela!'
    redirect_to @tabela_preco
  else
    flash[:alert] = 'Erro'
    render :new
  end
end

  def new
    @tabela_preco = TabelaPreco.new
    @hoteis = Hotel.all
    @tipo_clientes = TipoCliente.all
    @periodos = Periodo.all
  end

 
  def update
    if @tabela_preco.update(tabela_preco_params)
      redirect_to @tabela_preco
    else
      render :edit
    end
  end
  
  def edit
    @tabela_precos = TabelaPreco.all
    @hoteis = Hotel.all
    @tipo_clientes = TipoCliente.all
    @periodos = Periodo.all
  end

  def destroy
    @tabela_preco.destroy
    redirect_to @tabela_preco, notice: "Preço excluido com sucesso na tabela!"
  end
end

private

def tabela_preco_params
  params.require(:tabela_preco).permit(:hotel_id, :tipo_cliente_id, :periodo_id, :preco)
end

def set_find
   @tabela_preco = TabelaPreco.find(params[:id])
end

app/controllers/tipo_cliente_controller.rb
class TipoClienteController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotel_helper.rb
module HotelHelper
end

app/helpers/periodo_helper.rb
module PeriodoHelper
end

app/helpers/reserva_helper.rb
module ReservaHelper
end

app/helpers/tabela_preco_helper.rb
module TabelaPrecoHelper
end

app/helpers/tipo_cliente_helper.rb
module TipoClienteHelper
end

app/views/home/index.html.erb
<h1>Hotel TW </h1>
<p>Seja Bem vindo!</p>

<ul class="nav flex-column">
  <li><%= link_to "Reservas", reservas_path %></li>
  <li><%= link_to "Tabela de Preco", tabela_precos_path %></li>
</ul>

app/views/home/show.html.erb
<h1>home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelTw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservas/_form.html.erb
<% if @reserva.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @reserva.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>

<%# <%= @formatted_data1 %><br> 
<%# <%= @formatted_data2 %><br> 
<%# <%= @time_data1 %><br> 
<%# <%= @time_data2 %><br><br> 
<%# Dias Corridos: <%= @differ %><br>
<%# Dias de semana: <%= @weekdays %><br> 
<%# Dias de Fim de semana: <%= @weekend_days %><br><br> 


<%= form_for(reserva) do |f| %>
  
    <%= f.label :tipo_cliente_id %>
    <%= f.collection_select(:tipo_cliente_id, @tipo_clientes, :id, :type_client) %><br>
  
    <%= f.label :date_starting %>
    <%= f.text_field :date_starting %><br>
  
    <%= f.label :date_exit %>
    <%= f.text_field :date_exit %><br>

    <%= f.submit class:'btn btn-primary' %>
  
<% end %>

app/views/reservas/edit.html.erb
<h1>Alterar Reserva</h1>
<%= render partial: "form", locals: {reserva: @reserva} %>

<br><br><br>   
<%= link_to 'Voltar', reservas_path %>

app/views/reservas/index.html.erb
<h1>Hotel TW - Reservas Online</h1>
<p>Reservas Cadastradas</p>

<%if @reservas.present? %>
	  <p>Exibindo Todas Reservas Realizadas</p>
	  <!-- table width="100%" -->
		<table class="table table-hover">
	    <tr>
	      <td scope="col">Tipo de Cliente:</td>
	      <td scope="col">Data Inicial: </td>
	      <td scope="col">Data Final:</td>
	    </tr>
	    <%@reservas.each do |reserva|%>
	    <tr>
	      <td><%=reserva.tipo_cliente.type_client%></td>
	      <td><%=reserva.date_starting%></td>
	      <td><%=reserva.date_exit%></td>
	      <td>
	        <%= link_to "Editar", edit_reserva_path(reserva[:id]) %> 
	        <%= link_to "Deletar", reserva_path(reserva[:id]), :method => :delete %>
	      </td>
	    </tr>
	   <%end%>
	  </table>
	<%else%>
	  <p>Não existem Reservas realizadas</p>
	<%end%>

<ul class="nav flex-column">
  <li> <%= link_to 'Voltar', root_path %>  </li >
  <li><%= link_to "Nova Reserva", new_reserva_path %></li>
</ul>
<br>

app/views/reservas/new.html.erb
<p>New Reservation</p>
<%= render partial: "form", locals: {reserva: @reserva} %>

<br><br><br>   
<%= link_to 'Voltar', reservas_path %>

app/views/reservas/show.html.erb
<h1>Detalhes da Reserva</h1>
   
Tipo do Cliente: <%= @reserva.tipo_cliente.type_client %> <br> 
Data de Entrada: <%= @reserva.date_starting %><br>
Data de Saída: <%= @reserva.date_exit %><br>

<h5>
Total de dias reservados: <%= @differ %><br>
Total de dias de semana: <%=  @weekdays %><br>
Total dias de Fim de semana: <%= @weekend_days %><br>

</h5>
<%= link_to 'Editar', edit_reserva_path(@reserva) %>
<%= link_to 'Deletar', reserva_path(@reserva), method: :delete, data: { confirm: "Confirma exclusão da Reserva: #{@reserva.id}?" } %> 
<%= link_to 'Voltar', reservas_path %>

<br><br>

<!-- em caso de empate de valores a classificação do hotel deve ser prevalecida na escolha -->
Melhor escolha: <br>
<%= @tabela_preco_total.sort_by{|menor_preco| menor_preco[:total]}.first %><br> <br>

Semana: <br>
<%= @tabela_preco_semana %><br> <br>

Fim de semana: <br>
<%= @tabela_preco_fds %><br>

app/views/tabela_precos/_form.html.erb
<% if @tabela_preco.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @tabela_preco.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>

<%= form_for(tabela_preco) do |f| %>

    <%= f.label :hotel_id %>
    <%= f.collection_select(:hotel_id, @hoteis, :id, :nome) %><br>
  
    <%= f.label :tipo_cliente_id %>
    <%= f.collection_select(:tipo_cliente_id, @tipo_clientes, :id, :type_client) %><br>

     <%= f.label :periodo_id %>
    <%= f.collection_select(:periodo_id, @periodos, :id, :periodo) %><br>
  
    <%= f.label :preco %>
    <%= f.text_field :preco %><br>

    <%= f.submit class:'btn btn-primary' %>
  
<% end %>

app/views/tabela_precos/edit.html.erb
<h1>Alterar Preço na Tablea</h1>
<%= render partial: "form", locals: {tabela_preco: @tabela_preco} %>

<br><br><br>   
<%= link_to 'Voltar', tabela_precos_path %>

app/views/tabela_precos/index.html.erb
<h1>Hotel TW - Reservas Online</h1>
<p>Tabela de Preços</p>

<%if @tabela_precos.present? %>
	  <p>Exibindo Preços na Tabela</p>
	  <!-- table width="100%" -->
		<table class="table table-hover">
	    <tr>
	      <td scope="col">Hotel:</td>
	      <td scope="col">Tipo de Cliente: </td>
	      <td scope="col">Periodo:</td>
        <td scope="col">Preço:</td>
	    </tr>
	    <%@tabela_precos.each do |tabela_preco|%>
	    <tr>
	      <td><%=tabela_preco.hotel.nome %></td>
	      <td><%=tabela_preco.tipo_cliente.type_client%></td>
	      <td><%=tabela_preco.periodo.periodo%></td>
        <td><%=tabela_preco.preco %></td>
	      <td>
	        <%= link_to "Editar", edit_tabela_preco_path(tabela_preco[:id]) %>  
	        <%= link_to "Deletar", tabela_preco_path(tabela_preco[:id]), :method => :delete %> 
	      </td>
	    </tr>
	   <%end%>
	  </table>
	<%else%>
	  <p>Não existem Preços cadastrados an tabela.</p>
	<%end%>

<ul class="nav flex-column">
  <li><%= link_to "Incluir Preço na Tabela", new_tabela_preco_path %></li>
</ul>

<br><br><br>   
    <%= link_to 'Voltar', root_path %>

app/views/tabela_precos/new.html.erb
<p>Novo Preço para Hotel</p>
<%= render partial: "form", locals: {tabela_preco: @tabela_preco} %>

<br><br>   
<%= link_to 'Voltar', tabela_precos_path %>

app/views/tabela_precos/show.html.erb
<h1>Detalhes do Preco Incluso na Tadela</h1>
   
Hotel: <%= @tabela_preco.hotel.nome %> <br> 
Tipo de Cliente: <%= @tabela_preco.tipo_cliente.type_client %><br>
Periodo: <%= @tabela_preco.periodo.periodo %><br>
Preço: <%= @tabela_preco.preco %><br>


<%= link_to 'Editar', edit_tabela_preco_path(@tabela_preco) %>
<%= link_to 'Deletar', tabela_preco_path(@tabela_preco), method: :delete, data: { confirm: "Confirma exclusão do Preço dna Tabela #{@tabela_preco.id}?" } %> 
<%= link_to 'Voltar', tabela_precos_path %>

  